baseURL = "https://azure.github.io/azure-monitor-baseline-alerts"
title = "Azure Monitor Baseline Alerts"
theme = "hugo-theme-relearn"
themesDir = "docs/themes"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[module]
  [[module.mounts]]
    source = 'docs/content'
    target = 'content'
  [[module.mounts]]
    source = 'docs/static'
    target = 'static'
  [[module.mounts]]
    source = 'docs/layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'docs/data'
    target = 'data'
  [[module.mounts]]
    source = 'docs/assets'
    target = 'assets'
  [[module.mounts]]
    source = 'docs/i18n'
    target = 'i18n'
  [[module.mounts]]
    source = 'docs/archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = 'services'
    target = 'static/services'
    excludeFiles = ['**/_index.json']
  [[module.mounts]]
    source = 'services'
    target = 'content/services'
    excludeFiles = ['**/*.json', '**/README.md']
  [[module.mounts]]
    source = 'services'
    target = 'data'
    includeFiles = ['**/alerts.yaml']
  [[module.mounts]]
    source = 'services'
    target = 'static'
    includeFiles = ['amba-alerts.*']
  [[module.mounts]]
    source = 'artifacts'
    target = 'content/artifacts'
    includeFiles = ['**/*.json', '**/*.bicep']

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[taxonomies]
  tag = "tags"
