# logo image, direction and title
logo = { src = 'images/amba_logo.png' } # a global resource called `/images/logo.<TYPE>` will be selected automatically; nevertheless if you want to color an SVG it has to be inlined and so must be set manually here
direction = 'column'
linkTitle = "Azure Monitor\nBaseline Alerts "

# AMBA Dev mode settings
ambaDevMode = false

# AMBA CUAID
ambaTelemetryPid = "pid-8bb7cf8a-bcf7-4264-abcb-703ace2fc84d"

# menu and submenu settings
alwaysopen = false
collapsibleMenu = true

# landing page
disableLandingPageButton = true

# page meta & search
hideAuthorName = true
hideAuthorDate = true
hideAuthorEmail = true
disableSearchHiddenPages = true
