# title
linkTitle = "Azure Monitor\nBaseline Alerts"

# logo
logo =  {  src = '/images/amba_logo.png', direction = 'row' }

# AMBA Dev mode settings
ambaDevMode = false

# AMBA CUAID
ambaTelemetryPid = "pid-8bb7cf8a-bcf7-4264-abcb-703ace2fc84d"

# menu and submenu settings
alwaysopen = false
collapsibleMenu = true

# landing page
disableLandingPageButton = true

# page meta & search
hideAuthorName = true
hideAuthorDate = true
hideAuthorEmail = true
disableSearchHiddenPages = true
disableNextPrev = true
disableToc = true

themeVariant = [
	{ identifier = 'relearn-auto',  name = 'Relearn Light/Dark', auto = [ 'relearn-light', 'relearn-dark' ] },
	{ identifier = 'relearn-dark'   },
	{ identifier = 'relearn-light'  }
]
